[package]
name = "trigobot-rs"
version = "0.1.0"
authors = ["DMaxter <daniel_matos@outlook.pt>"]
edition = "2018"

[dependencies]
bincode  = "1.3"
dotenv   = "0.15"
serde    = { version = "1.0", features = ["derive"] }
serenity = { version = "0.10", default_features = false, features = ["client", "gateway", "model", "rustls_backend"] }
tokio    = { version = "1.8", features = ["macros", "rt-multi-thread"] }
