name: Rust Build and Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_check:
    name: Trigobot Carcinized
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v1


      - name: Build
        run: cargo build --verbose

      - name: Clippy Check
        run: cargo clippy -- -Dclippy::all --verbose

      - name: Format Check
        run: cargo fmt --all -- --check
